language: php
php:
  - '7.3.5'

services:
  - mysql

install:
  - composer install --no-interaction
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('test') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migration:migrate --env=test --no-interaction

script:
  - php bin/phpunit